### ISSUE TITLE
是不是只能用微信，不能用wechat？

### ISSUE THREAD

**Issue by calmcat2** [AutumnWhj/ChatGPT-wechat-bot#100]
新注册wechat账户扫码一直显示错误“Service unavailable for this account.”

**Comment by evolay** [comment]
新账户需要开通支付才能登录电脑版本，可以先尝试登录电脑版本成功再尝试这个。

**Comment by calmcat2** [comment]
wechat开通支付，能登陆电脑版本还是不行。应该是要国内的微信可登陆网页版才行吧。

**Comment by AutumnWhj** [comment]
应该都是可以的 可以再试试

**Comment by yinzixie** [comment]
wechat电脑版能登录，这个就不行。
