### ISSUE TITLE
请问怎么在微信使用chatGPT聊天机器人

### ISSUE THREAD

**Issue by getGitxxx** [AutumnWhj/ChatGPT-wechat-bot#11]
按照教程能够正常在iterm2终端正常登陆，但是手机上看不到chatGPT的聊天机器人，在iterm2里输入消息回车也没有任何反应，一定是我打开的方式不对，请指教🙏🏻

**Comment by AutumnWhj** [comment]
@getGitxxx  你好， 你得准备两个微信，用你的微信向 终端扫码后登录的微信发消息，这样就会收到ChatGPT的回复。

**Comment by getGitxxx** [comment]
> 

好的，我试试，多谢啦
