### ISSUE TITLE
请问一下，每次重启都会把之前的问题重新回答一遍，有什么办法能解决吗？

### ISSUE THREAD

**Issue by lzj960515** [AutumnWhj/ChatGPT-wechat-bot#110]
我在微信上问了个问题，后面每次重启程序他都会再回答一次，我用了reset方法也无法解决。请问一下怎么才能解决这个问题？

<img width="616" alt="image" src="https://user-images.githubusercontent.com/38074718/216878886-fb739512-418d-4b58-b566-650f41ed3aea.png">

**Comment by zhukai242** [comment]
同样的问题，请问怎么解决

**Comment by lzj960515** [comment]
没问题了，这个是因为机器人这边的微信号的消息我一直没看，导致每次重启都会重新读一遍未读的微信消息。

**Comment by lzj960515** [comment]
> 同样的问题，请问怎么解决

把消息看了就行。
