### ISSUE TITLE
npm i时报错怎么办啊

### ISSUE THREAD

**Issue by lycnb66** [AutumnWhj/ChatGPT-wechat-bot#118]
Debugger attached.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated puppeteer@13.7.0: < 18.1.0 is no longer supported
[##################] | reify:rxjs: timing reifyNode:node_modules/ix Completed in 10437ms

**Comment by samulo7** [comment]
nodejs版本太旧
