### ISSUE TITLE
似乎没有办法记住上下文，在AI那边是可以的

### ISSUE THREAD

**Issue by zenglincient** [AutumnWhj/ChatGPT-wechat-bot#12]
好像每次的聊天返回都是独立的
![如图](https://biu-cn.dwstatic.com/zbshenqi/20221207/0efd34c643e978a8e0d2fa5c870e5bf5.png?w=1738&h=1130)

**Comment by HandsomeWu6** [comment]
似乎是的

**Comment by askerlee** [comment]
context似乎是存在cookie里的。是不是client这边没有更新cookie？

**Comment by zenglincient** [comment]
> context似乎是存在cookie里的。是不是client这边没有更新cookie？

这个倒是没想到，请问有知道是哪个cookie么？还是一股脑更新就好了？

**Comment by askerlee** [comment]
这个理应是程序自动更新的。但是不知道这个repo有没有这么做

**Comment by zenglincient** [comment]
> 这个理应是程序自动更新的。但是不知道这个repo有没有这么做

确实如此，cookie中的【__Secure-next-auth.session-token】会经常更新。

**Comment by taacc** [comment]
看了一下代码，new ChatGPTAPI似乎只需要单例，还有chatgpt repo更新了conversation api，可以用那个试一下支不支持上下文

**Comment by AutumnWhj** [comment]
@zenglincient 现在已支持上下文
