### ISSUE TITLE
断开重新 npm dev run以后会把之前发给私聊的人的消息全部重新发一遍

### ISSUE THREAD

**Issue by zyune** [AutumnWhj/ChatGPT-wechat-bot#123]

**Comment by CodePythonFollow** [comment]
let startTime = new Date();
initProjest();
async function onMessage(msg) {
  if (msg.date() < startTime) {
    console.log("排除已经发送的消息");
    return;
  }
***
}
修改成这样就好了.

**Comment by 17huiwei** [comment]
我也遇到这问题了，吓我一跳

**Comment by 17huiwei** [comment]
> let startTime = new Date(); initProjest(); async function onMessage(msg) { if (msg.date() < startTime) { console.log("排除已经发送的消息"); return; }
> 
> } 修改成这样就好了.

请问这是改哪里？

**Comment by L1atte** [comment]
> > let startTime = new Date(); initProjest(); async function onMessage(msg) { if (msg.date() < startTime) { console.log("排除已经发送的消息"); return; }
> > } 修改成这样就好了.
> 
> 请问这是改哪里？

/src/index.ts 目录下，不过他有个typo，是
`initProject();`

**Comment by zyune** [comment]
大家的建议非常管用！

**Comment by AutumnWhj** [comment]
已更新代码 感谢
