### ISSUE TITLE
你需要开通微信支付，才可继续操作

### ISSUE THREAD

**Issue by Cabbage-Leon** [AutumnWhj/ChatGPT-wechat-bot#124]
是否有隐患？
![1675751780447](https://user-images.githubusercontent.com/31495215/217165105-31d1885e-45a6-47fb-9cf7-669187548023.jpg)

**Comment by huluohu** [comment]
开通微信支付的目的是要你实名认证，所以没啥风险

**Comment by 0x00A0** [comment]
没实名的微信不允许扫码登录

**Comment by AutumnWhj** [comment]
@0x00A0 正解
