### ISSUE TITLE
上下文串的问题

### ISSUE THREAD

**Issue by huluohu** [AutumnWhj/ChatGPT-wechat-bot#125]
在多个群里聊天，上下文会串台。
比如在A群问他关于造价工作的总结，机器人回复后，紧接着在B群直接@机器人 “还有呢？”，就会把A群的回复返回给B群

**Comment by AutumnWhj** [comment]
@huluohu 已修复

**Comment by huluohu** [comment]
> @huluohu 已修复

感谢大佬。
另外还有个问题：dockerfile里面有两个命令，在package.json里没没定义，麻烦大佬修复
1、RUN  npm run puppet-install
2、RUN npm run build
