### ISSUE TITLE
登录微信超时，有人遇到这个问题吗？

### ISSUE THREAD

**Issue by laosuan** [AutumnWhj/ChatGPT-wechat-bot#13]
details: 'Error: WatchdogAgent reset: lastFood: "{"data":{"code":201,"url":"xxx"},"timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (file:///xxx/ChatGPT-wechat-bot/node_modules/wechaty-puppet/dist/esm/src/agents/watchdog-agent.js:45:39)\n' +
    '    at Watchdog.emit (node:events:390:28)\n' +
    '    at Timeout._onTimeout (file:///xxx/ChatGPT-wechat-bot/node_modules/watchdog/dist/esm/src/watchdog.js:81:18)\n' +
    '    at listOnTimeout (node:internal/timers:557:17)\n' +
    '    at processTimers (node:internal/timers:500:7)'

**Comment by laosuan** [comment]
小号没发登录，大号能登录，意思被风控。

**Comment by AutumnWhj** [comment]
@laosuan  删除根目录下的 wechaty-puppet-wechat.memory-card.json 文件，再试试？

**Comment by taacc** [comment]
wechat限制有一些小号不能登录web微信，no idea。。。
