### ISSUE TITLE
api疑似不能使用？

### ISSUE THREAD

**Issue by Enderfga** [AutumnWhj/ChatGPT-wechat-bot#15]
1|bundle.esm  | Error: ChatGPTAPI error 503
1|bundle.esm  |     at fetchSSE (file:///home/admin/ChatGPT-wechat-bot/node_modules/.pnpm/chatgpt@2.0.1/node_modules/chatgpt/build/index.js:70:11)
1|bundle.esm  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)

我使用pm2后台运行，突然不会回复了，终端显示上述内容

**Comment by AutumnWhj** [comment]
@Enderfga 我用pm2试了下 没问题。node版本是 v16.17.0
<img width="790" alt="image" src="https://user-images.githubusercontent.com/39156049/206220522-e98d9569-0bc7-48c2-9f2f-4055ba2b9d3a.png">

**Comment by Enderfga** [comment]
经检查是token过期导致的
