### ISSUE TITLE
不是很聪明，ChatGPT版本略低？

### ISSUE THREAD

**Issue by hrk1988** [AutumnWhj/ChatGPT-wechat-bot#152]
目前通过API的ChatGPT版本是2.1，不知道网页版的是多少，但在回答问题的质量上差距有点大，有方法增加它智商吗？

**Comment by hrk1988** [comment]
看了一下，API使用的模型是text-chat-davinci-002，网页使用的模型是text-davinci-003，作者能切换上去吗？或者切换后有什么影响不？

**Comment by Roksolana969** [comment]
你的版本是多少
答：openai V1.0

**Comment by huluohu** [comment]
> 看了一下，API使用的模型是text-chat-davinci-002，网页使用的模型是text-davinci-003，作者能切换上去吗？或者切换后有什么影响不？

你搞反了。

**Comment by a289459798** [comment]
确实不太聪明，简历都不会写

**Comment by hrk1988** [comment]
> 

前面看错了，都使用了chatgpt这个库，发请求时设置模型就是text-davinci-003，但和网页端的差距怎么这么大……
具体有什么设置上的区别吗？

**Comment by huluohu** [comment]
> > 
> 
> 前面看错了，都使用了chatgpt这个库，发请求时设置模型就是text-davinci-003，但和网页端的差距怎么这么大…… 具体有什么设置上的区别吗？

openai官方网页端用的是text-davinci-002-render，跟api里的也不一样，不对外开放。

**Comment by a289459798** [comment]
https://github.com/fuergaosi233/wechat-chatgpt
这个项目比较聪明

**Comment by fateplayer** [comment]
> 这个项目比较聪明

这个项目报错400

**Comment by hrk1988** [comment]
> 

这项目使用的也是chatgpt这个库，理论上都半斤半两，明天我试试

**Comment by a289459798** [comment]
> > 
> 
> 这项目使用的也是chatgpt这个库，理论上都半斤半两，明天我试试

我试了确实要聪明不少，但是经常会被限流

**Comment by cy920820** [comment]
> https://github.com/fuergaosi233/wechat-chatgpt 这个项目比较聪明

这项目谷歌登录都不支持，玩毛

**Comment by AutumnWhj** [comment]
新model text-chat-davinci-002-sh-alpha-aoruigiofdj83 聪明了点

**Comment by woltium** [comment]
> 新model text-chat-davinci-002-sh-alpha-aoruigiofdj83 聪明了点

i have tried that model :

export function initChatGPT() {
  chatGPT = new ChatGPTAPI({
    apiKey: config.OPENAI_API_KEY,
    completionParams: {
      model: 'text-chat-davinci-002-sh-alpha-aoruigiofdj83',
    },
  });
}

but failed:

ChatGPTError: ChatGPT error 404: {
    "error": {
        "message": "That model does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

how to use that model?
