### ISSUE TITLE
如何设置回复中文？

### ISSUE THREAD

**Issue by KevinInce** [AutumnWhj/ChatGPT-wechat-bot#154]
![image](https://user-images.githubusercontent.com/27195203/217488496-a4d7aabe-38a5-4690-8411-5eaa453e6a60.png)
我有点绷不住了哈哈

**Comment by huluohu** [comment]
跟他说：请设置你的语言为中文

**Comment by KevinInce** [comment]
问题已解决

**Comment by joisonwk** [comment]
> 

怎么解决的呢？ 我也遇到这个问题
