### ISSUE TITLE
Module '"wechaty"' has no exported member 'WechatyBuilder'

### ISSUE THREAD

**Issue by chingfeng2021** [AutumnWhj/ChatGPT-wechat-bot#156]
这个错误见过吗

**Comment by elcieloboy** [comment]
见过，我直接跟你同问

**Comment by huluohu** [comment]
> 这个错误见过吗

升级node到v18+

**Comment by Dboy233** [comment]
> > 这个错误见过吗
> 
> 升级node到v18+

我的版本就是v18+
![image](https://user-images.githubusercontent.com/37604230/217580492-947c369e-f405-4e07-ba02-c6db96d09773.png)

**Comment by chunyeman** [comment]
return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/index.ts:1:10 - error TS2305: Module '"wechaty"' has no exported member 'WechatyBuilder'.

1 import { WechatyBuilder } from 'wechaty';
一样

**Comment by chingfeng2021** [comment]
你要用ubuntu，不然就会报错
