### ISSUE TITLE
登录微信没有反应

### ISSUE THREAD

**Issue by Nabyssache** [AutumnWhj/ChatGPT-wechat-bot#159]
https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Flogin.weixin.qq.com%2Fl%2FYdIZlUn9bg%3D%3D
10:10:04 WARN PuppetWatchdogAgent start() reset() reason: {"data":{"code":201,"url":"https://login.weixin.qq.com/qrcode/YdIZlUn9bg=="},"timeoutMilliseconds":60000}
file:///D:/DLproject/all_code/pre_computemap/chatgpt_wechat/ChatGPT-wechat-bot/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65
      this.puppet.emit('error', new Error(
                                ^
GError: WatchdogAgent reset: lastFood: "{"data":{"code":201,"url":"https://login.weixin.qq.com/qrcode/YdIZlUn9bg=="},"timeoutMilliseconds":60000}"
    at Watchdog.reset (file:///D:/DLproject/all_code/pre_computemap/chatgpt_wechat/ChatGPT-wechat-bot/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
    at Watchdog.emit (node:events:513:28)
    at Watchdog.emit (node:domain:489:12)
    at Timeout._onTimeout (file:///D:/DLproject/all_code/pre_computemap/chatgpt_wechat/ChatGPT-wechat-bot/node_modules/watchdog/src/watchdog.ts:115:12)        
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":{"code":201,"url":"https://login.weixin.qq.com/qrcode/YdIZlUn9bg=="},"timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (file:///D:/DLproject/all_code/pre_computemap/chatgpt_wechat/ChatGPT-wechat-bot/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
    '    at Watchdog.emit (node:events:513:28)\n' +
    '    at Watchdog.emit (node:domain:489:12)\n' +
    '    at Timeout._onTimeout (file:///D:/DLproject/all_code/pre_computemap/chatgpt_wechat/ChatGPT-wechat-bot/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
    '    at listOnTimeout (node:internal/timers:564:17)\n' +
    '    at processTimers (node:internal/timers:507:7)'
}

**Comment by Nabyssache** [comment]
没事了，就是微信的问题，微信无法登录桌面

**Comment by f-jun666** [comment]
> 没事了，就是微信的问题，微信无法登录桌面

我也是这种情况，就是不能用了吗

**Comment by Nabyssache** [comment]
没事了，就是微信的问题，微信无法登录桌面

> > 没事了，就是微信的问题，微信无法登录桌面
> 
> 我也是这种情况，就是不能用了吗

是的，换个能登陆桌面系统的微信就可以了

**Comment by f-jun666** [comment]
> 没事了，就是微信的问题，微信无法登录桌面
> 
> > > 没事了，就是微信的问题，微信无法登录桌面
> > 
> > 
> > 我也是这种情况，就是不能用了吗
> 
> 是的，换个能登陆桌面系统的微信就可以了

可能是实名认证问题，第一次用的微信没有实名认证，换个微信可以了

**Comment by f-jun666** [comment]
哥们：你使用起来顺利吗？我这边私聊可以，但是群里没法接受到信息

**Comment by Nabyssache** [comment]
> 哥们：你使用起来顺利吗？我这边私聊可以，但是群里没法接受到信息

反应非常快，快的离谱，群里也可以收到的。模型应该是gpt3?或者更差的模型，感觉不太智能，和chat.openai里面的chatgpt不太一样。
