### ISSUE TITLE
使用 pm2 在 ubuntu 18.04.6 LTS 上启动 

### ISSUE THREAD

**Issue by cy920820** [AutumnWhj/ChatGPT-wechat-bot#160]
使用命令 `pm2 start npm -- run dev --watch`  发现循环出现微信登录二维码，一直刷不停

**Comment by cy920820** [comment]
![image](https://user-images.githubusercontent.com/21211512/217706791-fd1f5847-96b5-4d7f-beac-c30a63ca79a9.png)

**Comment by huluohu** [comment]
你扫一个就不刷了

**Comment by cy920820** [comment]
> 你扫一个就不刷了

根本没空让你扫

**Comment by 1tex** [comment]
用screen命令试试吧

**Comment by cy920820** [comment]
> 用screen命令试试吧

我说的是二维码被刷新的很快，你根本来不及操作就已经失效了
