### ISSUE TITLE
我的回复好像有点不一样？

### ISSUE THREAD

**Issue by juju486** [AutumnWhj/ChatGPT-wechat-bot#161]
![1675913143440](https://user-images.githubusercontent.com/67678038/217710206-303b53e2-73b2-4460-b117-dff57e8f5f58.png)

无论问啥回复都很短

**Comment by cy920820** [comment]
你想要多长？？？

**Comment by juju486** [comment]
> 你想要多长？？？

和示例图不一样吧，就是感觉是另一个模型。
