### ISSUE TITLE
15:10:48 WARN PuppetWeChat friendshipRawPayload？？？

### ISSUE THREAD

**Issue by Eacolt** [AutumnWhj/ChatGPT-wechat-bot#165]
请问这是什么情况：
Current time:Thu Feb 09 2023 15:10:48 GMT+0800 (中国标准时间)
Automatic robot chat mode has been activated
15:10:48 WARN PuppetWeChat friendshipRawPayload(5402025989305233578)
15:10:48 WARN PuppetWeChat friendshipRawPayload(6312322711524372425)
15:10:49 WARN PuppetWeChat friendshipRawPayloadParser([object Object])
15:10:49 WARN PuppetWeChat friendshipRawPayloadParser([object Object])
微信聊天没任何回复，出现PuppetWeChat friendshipRawPayloadParser这样的字段

**Comment by GaleForceWYL21** [comment]
我也遇到同样的问题，重启才能解决
