### ISSUE TITLE
apikey 送的额度撑不了多久，建议使用账号密码

### ISSUE THREAD

**Issue by yangchuansheng** [AutumnWhj/ChatGPT-wechat-bot#172]
建议使用这个项目：https://github.com/bytemate/chatapi

**Comment by huluohu** [comment]
> 建议使用这个项目：https://github.com/bytemate/chatapi

额度是跟appkey绑定的吗？

**Comment by yangchuansheng** [comment]
> > 建议使用这个项目：[bytemate/chatapi](https://github.com/bytemate/chatapi)
> 
> 额度是跟appkey绑定的吗？

不是，这个用的不是 apikey，是 chatgpt 的 cookie，一直免费的

**Comment by huluohu** [comment]
> > > 建议使用这个项目：[bytemate/chatapi](https://github.com/bytemate/chatapi)
> > 
> > 
> > 额度是跟appkey绑定的吗？
> 
> 不是，这个用的不是 apikey，是 chatgpt 的 cookie，一直免费的

懂了，这个模拟登录web，相当于直接用官方私有的模型

**Comment by yangchuansheng** [comment]
> > > > 建议使用这个项目：[bytemate/chatapi](https://github.com/bytemate/chatapi)
> > > 
> > > 
> > > 额度是跟appkey绑定的吗？
> > 
> > 
> > 不是，这个用的不是 apikey，是 chatgpt 的 cookie，一直免费的
> 
> 懂了，这个模拟登录web，相当于直接用官方私有的模型

这个项目支持账号池

**Comment by skysu666** [comment]
不见了

**Comment by magicGina** [comment]
我就问了几个问题，连题目带回答总共261个汉字，计价事计了9000个token，这是为什么
