### ISSUE TITLE
使用 API key 的方式，接入的是GPT3而不是ChatGPT，对比测试后发现效果相差很大

### ISSUE THREAD

**Issue by iftaken** [AutumnWhj/ChatGPT-wechat-bot#177]
使用 API key 的方式，接入的是GPT3而不是ChatGPT，对比测试后发现效果相差很大，建议项目回退到使用token模拟网页提交的版本，这里OpenAI给出的API key并不能使用chatGPT能力

**Comment by AutumnWhj** [comment]
可以试试新的model  text-chat-davinci-002-sh-alpha-aoruigiofdj83

**Comment by dogton** [comment]
> 可以试试新的model text-chat-davinci-002-sh-alpha-aoruigiofdj83
这个模型似乎失效了？Java版本的SDK和这个仓库都提示404了
retry 3 times, error: Error: ChatGPT error 404: {
    "error": {
        "message": "That model does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

**Comment by dogton** [comment]
> 可以试试新的model text-chat-davinci-002-sh-alpha-aoruigiofdj83

这个模型似乎失效了，通过API的方式找不到模型，Java版本的和当前仓库都不行。具体提示如下：
retry 3 times, error: Error: ChatGPT error 404: {
    "error": {
        "message": "That model does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

**Comment by cyh-ustc** [comment]
故意混淆chatgpt和gpt3
骗star的
chatgpt没有api

**Comment by atifnimran** [comment]
Hello
