### ISSUE TITLE
私聊设定chatgpt的身份和功能后，群聊中这些设定不起作用，需要重新设定。另外，是否可以内置一些广告语或者类似功能？

### ISSUE THREAD

**Issue by hupojilulife** [AutumnWhj/ChatGPT-wechat-bot#178]
如题，这个问题不知道是不是已经有解决了而我不懂代码所以不会，还是尚未开始解决？

我在设想可行的商业化方式

但是不可能在有顾客的群聊中再调试chatgpt，所以是否可能在后台设置一些设定（比如chatgpt的角色，需要做哪方面的事情），在登录的那一刻chatgpt就按照预设的设定来展开。

同时，我看到市场上有体验群里，chatbot可以在特定时候额外说一句：去加xx微信，领取体验版之类的广告词。

不知道这些功能目前已经有了吗？代码太多，我是代码小白，能部署到微信上面已经是我的代码极限了 - -！

作者大佬或者有其他大佬可以留言私聊不？（github我也不是很熟，关注了作者，好像没有私信的地方？囧

**Comment by AutumnWhj** [comment]
你说的这些，要通过修改代码来支持

**Comment by cvpv** [comment]
是的，开源社区还是需要代码贡献者来维持项目进展。如果您不懂开发，可以提问题，但是可能采纳的情况，不会非常如意

**Comment by hupojilulife** [comment]
> 是的，开源社区还是需要代码贡献者来维持项目进展。如果您不懂开发，可以提问题，但是可能采纳的情况，不会非常如意

确实我贡献不了代码，我自己对着一点也很痛心。。不过我提这个issue的原因是担心是不是可以轻松做到这种功能，类似于改config一样简单修改一下就可以做到，而我不自知（我的水平仅限于安装和改config - -!）。

当然如果没有我也不会做单纯的伸手党，是希望联系作者，看看能不能付费帮我做修改

**Comment by hupojilulife** [comment]
> 你说的这些，要通过修改代码来支持

啊。。大佬回复了，这两天没上git，囧

不知道这个修改的工作量大吗？修改后的稳定吗？
可以加你私聊不？
