### ISSUE TITLE
Windows上如何进行

### ISSUE THREAD

**Issue by kevinwatson2** [AutumnWhj/ChatGPT-wechat-bot#179]
在Windows上用Anaconda里的的python Jupiter Notebook，是否可以使用这个ChatGPT-Wechat-bot? 看见README_ZH.md里的下面两行，好像是Linux的工具。请问应该如何处理，还是必须换环境？
```javascript
  // install dependencies
  npm i
  npm run dev
```

**Comment by AutumnWhj** [comment]
@kevinwatson2 首先得安装node 可以参考 https://www.runoob.com/nodejs/nodejs-install-setup.html

**Comment by kevinwatson2** [comment]
下载安装了，还是找不到npm应用，谢谢。等高手们发现新方法后再尝试了。在这里阅读了大家的讨论，受益匪浅，多谢！

**Comment by jisuxinkong** [comment]
1、https://zhuanlan.zhihu.com/p/507141208，按照这个链接的教程下载最新的python版本，安装。
2、然后快捷键win+r ，输入cmd，打开windows命令控制台，cd到项目目录下，如: cd D:/chatgpt-on-wechat
3、然后根据项目教程更改config,json
4、windows控制台输入，py app.py，回车后项目就运行起来了。

**Comment by kevinwatson2** [comment]
> 1、[https://zhuanlan.zhihu.com/p/507141208，按照这个链接的教程下载最新的python版本，安装。](https://zhuanlan.zhihu.com/p/507141208%EF%BC%8C%E6%8C%89%E7%85%A7%E8%BF%99%E4%B8%AA%E9%93%BE%E6%8E%A5%E7%9A%84%E6%95%99%E7%A8%8B%E4%B8%8B%E8%BD%BD%E6%9C%80%E6%96%B0%E7%9A%84python%E7%89%88%E6%9C%AC%EF%BC%8C%E5%AE%89%E8%A3%85%E3%80%82) 2、然后快捷键win+r ，输入cmd，打开windows命令控制台，cd到项目目录下，如: cd D:/chatgpt-on-wechat 3、然后根据项目教程更改config,json 4、windows控制台输入，py app.py，回车后项目就运行起来了。

请问你的python版本是什么？我的版本是3.10.9，刚查了一下网上最新版是3.11.2.  我的Anaconda的版本是23.1.0.  不清楚我是否需要再安装什么版本. 另外，你可以避免封号吗？谢谢！

**Comment by jisuxinkong** [comment]
看了一下是3.10.10，我没用过python，就是去官网上下了个最新版的64位安装包。我没有用Anaconda。我用的微信号是应该是10年的老号了，刚用了一天，没什么问题。

**Comment by jisuxinkong** [comment]
> > 1、[https://zhuanlan.zhihu.com/p/507141208，按照这个链接的教程下载最新的python版本，安装。](https://zhuanlan.zhihu.com/p/507141208%EF%BC%8C%E6%8C%89%E7%85%A7%E8%BF%99%E4%B8%AA%E9%93%BE%E6%8E%A5%E7%9A%84%E6%95%99%E7%A8%8B%E4%B8%8B%E8%BD%BD%E6%9C%80%E6%96%B0%E7%9A%84python%E7%89%88%E6%9C%AC%EF%BC%8C%E5%AE%89%E8%A3%85%E3%80%82) 2、然后快捷键win+r ，输入cmd，打开windows命令控制台，cd到项目目录下，如: cd D:/chatgpt-on-wechat 3、然后根据项目教程更改config,json 4、windows控制台输入，py app.py，回车后项目就运行起来了。
> 
> 请问你的python版本是什么？我的版本是3.10.9，刚查了一下网上最新版是3.11.2. 我的Anaconda的版本是23.1.0. 不清楚我是否需要再安装什么版本. 另外，你可以避免封号吗？谢谢！

看了一下是3.10.10，我没用过python，就是去官网上下了个最新版的64位安装包。我没有用Anaconda。我用的微信号是应该是10年的老号了，刚用了一天，没什么问题。

**Comment by kevinwatson2** [comment]
> 看了一下是3.10.10，我没用过python，就是去官网上下了个最新版的64位安装包。我没有用Anaconda。我用的微信号是应该是10年的老号了，刚用了一天，没什么问题。

谢谢！把我的python升级到3.10.10后还是同样的问题。请问为啥你的第4步改成如下？

  4、windows控制台输入，py app.py，回车后项目就运行起来了。

你的 app.py 里是什么？如不方便在这里说，请发到我的邮箱： kevinwat at gmail dot com。
你运行 npm run dev， 也看见SyntaxError: Unexpected token ':' 吗？多谢！

**Comment by jisuxinkong** [comment]
> 你的 app.py 里是什么？如不方便在这里说，请发到我的邮箱： kevinwat at gmail dot com。 你运行 npm run dev， 也看见SyntaxError: Unexpected token ':' 吗？多谢！

实在不好意思，我回复错项目了，我用的是这个项目。尴尬！！
https://github.com/zhayujie/chatgpt-on-wechat

**Comment by kevinwatson2** [comment]
@jisuxinkong never mind, thanks!
