### ISSUE TITLE
无法正常启动并且聊天

### ISSUE THREAD

**Issue by NikoYomi** [AutumnWhj/ChatGPT-wechat-bot#182]
![b3880b9a4a1c6fe8148338491cccdb6](https://user-images.githubusercontent.com/120245220/218247654-b08dab68-101e-4d3e-8b89-e7135e582294.png)
正常设置但是没办法运行。
看样子是链接成功了，但是又没成功。求解决
![552028f85f1b58e338b0aac082ee6ad](https://user-images.githubusercontent.com/120245220/218247658-aba0bcba-671d-402c-b28f-eb1514063d0c.png)

**Comment by aTong9** [comment]
同样的问题

**Comment by KaiserLord** [comment]
我也是，扫码登录了，但是并没有启动gpt

**Comment by My-Bloody-Valentine** [comment]
同样的，扫码登陆但是fetch失败，没法调用api
