### ISSUE TITLE
【扫码登录失败】抛错To continue, enable Weixin Pay first. 账号必须要开启微信支付吗？

### ISSUE THREAD

**Issue by KeyongLiu** [AutumnWhj/ChatGPT-wechat-bot#185]
# Log
23:18:24 WARN PuppetWeChatBridge onDialog() page.on(dialog) type:type() {
        return this._type;
    } message:To continue, enable Weixin Pay first.
file:///root/fun/chatgpt/ChatGPT-wechat-bot/node_modules/gerror/src/gerror/gerror.ts:69
      const e = new Error(payload)
                ^
GError: type() {
        return this._type;
    }(To continue, enable Weixin Pay first.)
    at Function.from (file:///root/fun/chatgpt/ChatGPT-wechat-bot/node_modules/gerror/src/gerror/gerror.ts:69:17)
    at Bridge.onDialog (file:///root/fun/chatgpt/ChatGPT-wechat-bot/node_modules/wechaty-puppet-wechat/src/bridge.ts:190:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'GError: type() {\n' +
    '        return this._type;\n' +
    '    }(To continue, enable Weixin Pay first.)\n' +
    '    at Function.from (file:///root/fun/chatgpt/ChatGPT-wechat-bot/node_modules/gerror/src/gerror/gerror.ts:69:17)\n' +
    '    at Bridge.onDialog (file:///root/fun/chatgpt/ChatGPT-wechat-bot/node_modules/wechaty-puppet-wechat/src/bridge.ts:190:31)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)'
}

# 提问
请问下这个日志是说微信号必须要开通微信支付吗？
其他人都是开通了微信支付才能扫码登录吗？
求告知，谢谢

**Comment by Eacolt** [comment]
你好，我也是这个问题，但是我的账号已经实名注册过了，也开通了微信支付，前天能登陆，现在就一直报这个错误，不知道什么原因啊

**Comment by KeyongLiu** [comment]
> 

是吗，你后面好了吗？ 看报错是要开通微信支付

**Comment by huluohu** [comment]
别搞了，会被封号的
