### ISSUE TITLE
扫码登录失败，求助

### ISSUE THREAD

**Issue by Eacolt** [AutumnWhj/ChatGPT-wechat-bot#187]
<img width="783" alt="image" src="https://user-images.githubusercontent.com/15901920/218290862-e58fde1e-1951-4226-94d9-9c0859b47afc.png">

npm run dev后生成了2个二维码，扫码后直接报错，提示登录失败一大堆错误，就挂了，请问如何解决？

**Comment by azuretimm** [comment]
> <img alt="image" width="783" src="https://user-images.githubusercontent.com/15901920/218290862-e58fde1e-1951-4226-94d9-9c0859b47afc.png">
> 
> npm run dev后生成了2个二维码，扫码后直接报错，提示登录失败一大堆错误，就挂了，请问如何解决？

你的微信账号大概率被限制发送消息了，看看你手机吧，按照提示发短信刷脸解封就好了

**Comment by Eacolt** [comment]
> > <img alt="image" width="783" src="https://user-images.githubusercontent.com/15901920/218290862-e58fde1e-1951-4226-94d9-9c0859b47afc.png">
> > npm run dev后生成了2个二维码，扫码后直接报错，提示登录失败一大堆错误，就挂了，请问如何解决？
> 
> 你的微信账号大概率被限制发送消息了，看看你手机吧，按照提示发短信刷脸解封就好了

还真是，感谢您的热情回复，好人一生平安
