### ISSUE TITLE
求助 start() starting puppet ... timeout

### ISSUE THREAD

**Issue by cyDione** [AutumnWhj/ChatGPT-wechat-bot#188]
run dev后一直timeout
16:12:59 WARN WechatyPuppetMixin start() starting puppet ... timeout
16:12:59 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(WechatEveryDay)
Start to log in wechat...
16:13:50 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
16:13:50 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
16:13:50 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

**Comment by Vater922** [comment]
我也是

**Comment by Vater922** [comment]
我解决了，需要一个实名认证过的微信帐号，没有实名的会timeout

**Comment by Vater922** [comment]
> 我也是

我解决了，需要一个实名认证过的微信帐号，没有实名的会timeout
