### ISSUE TITLE
openAI账户中免费额度计费狂飙

### ISSUE THREAD

**Issue by magicGina** [AutumnWhj/ChatGPT-wechat-bot#193]
我就问了几个问题，连题目带回答总共261个汉字，计价总共计了6000多个token，这是为什么？
<img width="643" alt="1676302685454" src="https://user-images.githubusercontent.com/88796282/218502620-d93e05a8-dbb2-4ab3-8fa9-5637dc362cfb.png">
![image](https://user-images.githubusercontent.com/88796282/218502902-90a47058-c81d-4b54-a47e-2bdfed771216.png)

**Comment by Kallycong** [comment]
一样，测试了大概十分钟这样，问了五六个问题，没了七千多token

**Comment by joisonwk** [comment]
奇怪，难道apikey被劫持用来问了其它问题

**Comment by joisonwk** [comment]
知道 为什么了，把chatgpt的debug打开看到他为什么消耗那么快了，原来它自动把前面问的prompt和responese 全部加入到下一条prompt里去了
