### ISSUE TITLE
Module '"wechaty"' has no exported member 'WechatyBuilder'.

### ISSUE THREAD

**Issue by cestoon** [AutumnWhj/ChatGPT-wechat-bot#196]
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/28974586/218996760-47a71c36-7500-41ef-902e-3cc468f48573.png">

**Comment by atifnimran** [comment]
Good

**Comment by cestoon** [comment]
你好，你的邮件已收到，我会尽快阅读并回复，谢谢！hi，your letter had been received and I'll give you feedback ASAP!TEL:13547920459
