### ISSUE TITLE
改了一份注入dll版机器人对接chatgpt的

### ISSUE THREAD

**Issue by sromwey** [AutumnWhj/ChatGPT-wechat-bot#199]
![image](https://user-images.githubusercontent.com/6755325/219308193-76413cc9-4681-4e53-a485-ba206205f640.png)
已经用https://github.com/cixingguangming55555/wechat-bot改了一份注入dll版机器人对接chatgpt的，现在能完美运行接入，需要的QQ群2118558下

**Comment by Kylin93CN** [comment]
可以上云服务器吗  win-server   - -，
