### ISSUE TITLE
各位大佬，这个是要付钱的意思吗？

### ISSUE THREAD

**Issue by AlexNtFound** [AutumnWhj/ChatGPT-wechat-bot#204]
![2023-02-18](https://user-images.githubusercontent.com/112302161/219921930-6aaa14d7-e38f-45e2-baf0-b15449efd8ee.png)

**Comment by cvpv** [comment]
一点前端基础都没有吗，建议先学下npm的使用方法... install命令要在项目路径下（有package配置文件的目录下）使用

**Comment by cvpv** [comment]
如果已经安装，直接执行npm run dev就行

**Comment by 0x00A0** [comment]
> 一点前端基础都没有吗，建议先学下npm的使用方法... install命令要在项目路径下（有package配置文件的目录下）使用

这哪是没前端基础,这是没计算机基础,建议先学习基础的计算机和编程再来github

**Comment by AlexNtFound** [comment]
> 如果已经安装，直接执行npm run dev就行
> 
> 

明白了，之前确实没了解过npm，不太确定它的运行位置，谢谢指教！

**Comment by AlexNtFound** [comment]
> > 一点前端基础都没有吗，建议先学下npm的使用方法... install命令要在项目路径下（有package配置文件的目录下）使用
> 
> 
> 
> 这哪是没前端基础,这是没计算机基础,建议先学习基础的计算机和编程再来github

谢谢你的批评，我会加强我的计算机知识的，也希望你在计算机领域也能越来越好
