### ISSUE TITLE
微信扫码登陆后报错

### ISSUE THREAD

**Issue by Luuuuuuuuu1** [AutumnWhj/ChatGPT-wechat-bot#209]
`https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Flogin.weixin.qq.com%2Fl%2Fgcmv-rxMrQ%3D%3D
02:07:32 WARN PuppetWatchdogAgent start() reset() reason: {"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}
file:///C:/Users/15416/Desktop/ChatGPT-wechat-bot/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65
      this.puppet.emit('error', new Error(
                                ^
GError: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"
    at Watchdog.reset (file:///C:/Users/15416/Desktop/ChatGPT-wechat-bot/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
    at Watchdog.emit (node:events:513:28)
    at Watchdog.emit (node:domain:489:12)
    at Timeout._onTimeout (file:///C:/Users/15416/Desktop/ChatGPT-wechat-bot/node_modules/watchdog/src/watchdog.ts:115:12)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (file:///C:/Users/15416/Desktop/ChatGPT-wechat-bot/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
    '    at Watchdog.emit (node:events:513:28)\n' +
    '    at Watchdog.emit (node:domain:489:12)\n' +
    '    at Timeout._onTimeout (file:///C:/Users/15416/Desktop/ChatGPT-wechat-bot/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
    '    at listOnTimeout (node:internal/timers:569:17)\n' +
    '    at processTimers (node:internal/timers:512:7)'
}
![Screenshot_20230223_020855](https://user-images.githubusercontent.com/112217276/220840811-6092bd06-db40-4adc-9389-aa1fea5f1e80.png)

**Comment by GaleForceWYL21** [comment]
我也遇到过类似的，手机上把之前已登陆的Pc端退了，然后重启即可

**Comment by 857193874** [comment]
我遇到了一样的问题，请问解决了吗？

**Comment by 857193874** [comment]
貌似必须使用经过实名认证的微信才可以
