### ISSUE TITLE
请大大更新gpt3.5

### ISSUE THREAD

**Issue by Creazygao** [AutumnWhj/ChatGPT-wechat-bot#213]
按gpt3.5的文档，尝试调了一下参数和地址，还是有不少问题，还请大大出手，支持一下gpt3.5-turbo

**Comment by zsj1zsj** [comment]
+1

**Comment by PKUcoldkeyboard** [comment]
修改一下open_ai_bot.py这个文件就好了，去官网看记录，成功用上gpt-3.5-turbo。
``` py
def reply_text(self, query, user_id, retry_count=0):
        try:
            # response = openai.Completion.create(
            #     model="text-davinci-003",  # 对话模型的名称
            #     prompt=query,
            #     temperature=0.9,  # 值在[0,1]之间，越大表示回复越具有不确定性
            #     max_tokens=1200,  # 回复最大的字符数
            #     top_p=1,
            #     frequency_penalty=0.0,  # [-2,2]之间，该值越大则更倾向于产生不同的内容
            #     presence_penalty=0.0,  # [-2,2]之间，该值越大则更倾向于产生不同的内容
            #     stop=["\n\n\n"]
            # )
            response = openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "user", "content": query},
                ]
            )
            res_content = response['choices'][0]['message']['content']
            # res_content = response['choices'][0]['message']['content'].strip().replace('<|endoftext|>', '')
            logger.info("[OPEN_AI] reply={}".format(res_content))
            return res_content
        except openai.error.RateLimitError as e:
            # rate limit exception
            logger.warn(e)
            if retry_count < 1:
                time.sleep(5)
                logger.warn("[OPEN_AI] RateLimit exceed, 第{}次重试".format(retry_count+1))
                return self.reply_text(query, user_id, retry_count+1)
            else:
                return "提问太快啦，请休息一下再问我吧"
        except Exception as e:
            # unknown exception
            logger.exception(e)
            Session.clear_session(user_id)
            return "请再问我一次吧"
```

**Comment by LuzhiHan** [comment]
大大，我们太菜了，这个文件都没找到在哪，请大大指教

**Comment by LuzhiHan** [comment]
> 修改一下open_ai_bot.py这个文件就好了，去官网看记录，成功用上gpt-3.5-turbo。
> 
> ```python
> def reply_text(self, query, user_id, retry_count=0):
>         try:
>             # response = openai.Completion.create(
>             #     model="text-davinci-003",  # 对话模型的名称
>             #     prompt=query,
>             #     temperature=0.9,  # 值在[0,1]之间，越大表示回复越具有不确定性
>             #     max_tokens=1200,  # 回复最大的字符数
>             #     top_p=1,
>             #     frequency_penalty=0.0,  # [-2,2]之间，该值越大则更倾向于产生不同的内容
>             #     presence_penalty=0.0,  # [-2,2]之间，该值越大则更倾向于产生不同的内容
>             #     stop=["\n\n\n"]
>             # )
>             response = openai.ChatCompletion.create(
>                 model="gpt-3.5-turbo",
>                 messages=[
>                     {"role": "user", "content": query},
>                 ]
>             )
>             res_content = response['choices'][0]['message']['content']
>             # res_content = response['choices'][0]['message']['content'].strip().replace('<|endoftext|>', '')
>             logger.info("[OPEN_AI] reply={}".format(res_content))
>             return res_content
>         except openai.error.RateLimitError as e:
>             # rate limit exception
>             logger.warn(e)
>             if retry_count < 1:
>                 time.sleep(5)
>                 logger.warn("[OPEN_AI] RateLimit exceed, 第{}次重试".format(retry_count+1))
>                 return self.reply_text(query, user_id, retry_count+1)
>             else:
>                 return "提问太快啦，请休息一下再问我吧"
>         except Exception as e:
>             # unknown exception
>             logger.exception(e)
>             Session.clear_session(user_id)
>             return "请再问我一次吧"
> ```

大大这个文件在哪个位置呀

**Comment by PKUcoldkeyboard** [comment]
> > 修改一下open_ai_bot.py这个文件就好了，去官网看记录，成功用上gpt-3.5-turbo。
> > ```python
> > def reply_text(self, query, user_id, retry_count=0):
> >         try:
> >             # response = openai.Completion.create(
> >             #     model="text-davinci-003",  # 对话模型的名称
> >             #     prompt=query,
> >             #     temperature=0.9,  # 值在[0,1]之间，越大表示回复越具有不确定性
> >             #     max_tokens=1200,  # 回复最大的字符数
> >             #     top_p=1,
> >             #     frequency_penalty=0.0,  # [-2,2]之间，该值越大则更倾向于产生不同的内容
> >             #     presence_penalty=0.0,  # [-2,2]之间，该值越大则更倾向于产生不同的内容
> >             #     stop=["\n\n\n"]
> >             # )
> >             response = openai.ChatCompletion.create(
> >                 model="gpt-3.5-turbo",
> >                 messages=[
> >                     {"role": "user", "content": query},
> >                 ]
> >             )
> >             res_content = response['choices'][0]['message']['content']
> >             # res_content = response['choices'][0]['message']['content'].strip().replace('<|endoftext|>', '')
> >             logger.info("[OPEN_AI] reply={}".format(res_content))
> >             return res_content
> >         except openai.error.RateLimitError as e:
> >             # rate limit exception
> >             logger.warn(e)
> >             if retry_count < 1:
> >                 time.sleep(5)
> >                 logger.warn("[OPEN_AI] RateLimit exceed, 第{}次重试".format(retry_count+1))
> >                 return self.reply_text(query, user_id, retry_count+1)
> >             else:
> >                 return "提问太快啦，请休息一下再问我吧"
> >         except Exception as e:
> >             # unknown exception
> >             logger.exception(e)
> >             Session.clear_session(user_id)
> >             return "请再问我一次吧"
> > ```
> 
> 大大这个文件在哪个位置呀

bot/openai/open_ai_bot.py

**Comment by PKUcoldkeyboard** [comment]
发现搞混了。。弄的是隔壁python项目的

**Comment by LuzhiHan** [comment]
> 发现搞混了。。弄的是隔壁python项目的

一直在努力的寻找，识图装的不那么菜。。。。

**Comment by wbbeyourself** [comment]
> 

哈哈哈哈 加油💪🏻  顺便把这个当做一个学习的机会呢

**Comment by AutumnWhj** [comment]
已更新 @ChpShy  感谢关注
