### ISSUE TITLE
retry 1 times, error: TypeError: fetch failed，如何解决，开了VPN全局代理也不行

### ISSUE THREAD

**Issue by xingyingshuailiangzheng** [AutumnWhj/ChatGPT-wechat-bot#217]
![image](https://user-images.githubusercontent.com/119168509/223383063-7ae967b8-3cd7-4568-a253-a9814d582a31.png)

**Comment by jiangyo** [comment]
我也遇到这个问题，请问你找到解决方法了吗？

**Comment by Jeremy233666** [comment]
请问解决了吗

**Comment by shenyimings** [comment]
用腾讯云函数香港服做代理转发，然后设置`basePath`
https://github.com/Ice-Hazymoon/openai-scf-proxy

**Comment by 853446764** [comment]
解决了吗

**Comment by howardzhh** [comment]
解决了吗

**Comment by AutumnWhj** [comment]
已解决 @853446764  看README 设置代理

**Comment by howardzhh** [comment]
您好，我已收到您的来信，会在近期尽快回复，感谢您的来信。
