### ISSUE TITLE
Login failed: Error(bot=Bot(848940689), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=) 2023-03-09 09:24:50 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(848940689), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=) net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(848940689), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)

### ISSUE THREAD

**Issue by Le1a** [AutumnWhj/ChatGPT-wechat-bot#219]
Login failed: Error(bot=Bot(848940689), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
2023-03-09 09:24:50 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(848940689), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(848940689), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)

**Comment by chengkhen** [comment]
求求怎么解决

**Comment by chengkhen** [comment]
我也这个问题

**Comment by AutumnWhj** [comment]
@chengkhen拉代码重新试试
