### ISSUE TITLE
求教使用方法

### ISSUE THREAD

**Issue by askerlee** [AutumnWhj/ChatGPT-wechat-bot#22]
是运行起来之后，拿自己微信扫码吗？我扫描之后微信说“当前账号无法使用该服务”。是需要为bot专门注册个机器人号吗？谢谢

**Comment by fj3224013877** [comment]
我注册了openai账号，但是我不知道docker，以及这个该如何使用，有大佬可以简单为我讲解一下吗

**Comment by johanazhu** [comment]
> 

就普通的微信号就可以，为了防止被封号，建议用小号

**Comment by johanazhu** [comment]
> 是运行起来之后，拿自己微信扫码吗？我扫描之后微信说“当前账号无法使用该服务”。是需要为bot专门注册个机器人号吗？谢谢

就普通的微信号就可以，为了防止被封号，建议用小号

**Comment by johanazhu** [comment]
> 我注册了openai账号，但是我不知道docker，以及这个该如何使用，有大佬可以简单为我讲解一下吗

按照 readme 中所述，先下载源代码，再配置 src/index.js 中的 token，再用 docker build 打包出wechatbot镜像，再用 docker run 开启一个容器

**Comment by AutumnWhj** [comment]
@askerlee @fj3224013877  可以按 @johanazhu 的顺序操作一下，若不适用docker 执行`npm run dev`前 记得先往 `src/index.js` 填入token哈。

**Comment by askerlee** [comment]
@AutumnWhj @johanazhu 谢谢，我的已经运行起来了，也看到QR code了，就是扫码之后不能登录 😢 不知道和“我是海外用户”有没有关系。另外我看别的bot说需要实名认证，但我已经认证了的

**Comment by AutumnWhj** [comment]
@askerlee  删除根目录的wechaty-puppet-wechat.memory-card.json 重新跑一下试试

**Comment by askerlee** [comment]
@AutumnWhj 没看到这个文件，看到一个类似名的WechatEveryDay.memory-card.json，删了之后扫码仍然提示一样的错误……

**Comment by askerlee** [comment]
知道了，是因为我用的wechat（海外版）扫码的。看到另一个repo里有人说wechat扫码会失败

**Comment by AutumnWhj** [comment]
nice

**Comment by askerlee** [comment]
@AutumnWhj 请问有什么修复的思路吗？我看了下海外版web微信QR的url：http://weixin.qq.com/x/ad2xqJmHqmegxJ4OhBtN
这个生成的QR： https://login.weixin.qq.com/l/YYHWcjBusA==
可以看到格式稍有不同，不知道替换以后会不会能work。
但我在整个repo里搜了 `login.weixin.qq.com`并替换了（删掉`login`，`l->x`），生成的QR仍然是`login.weixin.qq.com/l/`这样格式的。这个地址是写在别的什么地方了吗？谢谢

**Comment by mrmarktyy** [comment]
> 知道了，是因为我用的wechat（海外版）扫码的。看到另一个repo里有人说wechat扫码会失败

同wechat扫码无法登录，请问解决方法是什么？

**Comment by ozbillwang** [comment]
这个问题有解决吗？

**Comment by ozbillwang** [comment]
用了最新代码，还是一样的问题。 

另外，感觉就算用上了， 也用不了多久就会被封啊。 
https://github.com/AutumnWhj/ChatGPT-wechat-bot/issues/158

**Comment by ozbillwang** [comment]
![image](https://user-images.githubusercontent.com/8954908/236731829-2da782f8-b219-4ebc-8876-50babe766df8.png)
