### ISSUE TITLE
亲测，API被封后，账号也会被封禁

### ISSUE THREAD

**Issue by ShawnSheno** [AutumnWhj/ChatGPT-wechat-bot#222]
目前遇到被封的情况
API被封（已测）
一般是服务器ip不在OpenAI服务区域，比较好解决。国内有些云厂商海外服务器也不太行。
换成亚马逊云海外服务器即可。见https://www.pmssw.com/44.html

我开了个交流群，可以一起讨论下经验。
<img width="266" alt="image" src="https://user-images.githubusercontent.com/34580770/225943776-aae27545-9abf-4e29-a44c-b092514bc969.png">

**Comment by lovegnep** [comment]
超过200人了，求拉 lovegnepex

**Comment by mengyunzhu-git** [comment]
求拉一手 er1988
