### ISSUE TITLE
无法刷新authtoken

### ISSUE THREAD

**Issue by LFMJUN** [AutumnWhj/ChatGPT-wechat-bot#24]
> talker: Hypocrite content: 你好
> Error: ChatGPT failed to refresh auth token. TypeError: Cannot convert argument to a ByteString because the character at index 1032 has a value of 8230 which is greater than 255.
>     at ChatGPTAPI.refreshAccessToken (file:///root/ChatGPT-wechat-bot/node_modules/chatgpt/build/index.js:246:13)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async ChatGPTAPI.ensureAuth (file:///root/ChatGPT-wechat-bot/node_modules/chatgpt/build/index.js:212:12)
>     at async getChatGPTReply (file:///root/ChatGPT-wechat-bot/lib/bundle.esm.js:14:5)
>     at async replyMessage (file:///root/ChatGPT-wechat-bot/lib/bundle.esm.js:29:23)

**Comment by LFMJUN** [comment]
root@s7:~/ChatGPT-wechat-bot# node -v
v16.14.0

**Comment by LFMJUN** [comment]
![image](https://user-images.githubusercontent.com/47923014/206392282-da31e619-f291-47e6-82bf-25aaa0499f15.png)

**Comment by AutumnWhj** [comment]
@LFMJUN  您好， 在devtool 清空浏览器缓存，重新获取session token试试。

**Comment by LFMJUN** [comment]
感谢，可以了
