### ISSUE TITLE
如果能接入Moonshot AI开放平台就好了

### ISSUE THREAD

**Issue by LonePheasantWarrior** [AutumnWhj/ChatGPT-wechat-bot#269]
月之暗面的moonshot-v1模型感觉很好用

**Comment by xuzeyu91** [comment]
可以用one-api接入

**Comment by LonePheasantWarrior** [comment]
> 可以用one-api接入

是的.豆包的角色扮演机器人也不错,不过得修改下代码才能接进去,响应内容的格式稍有不同.有些麻烦,我更喜欢用docker启动,主打一个省事儿.希望后续作者能考虑下火山引擎下的bot接入
