### ISSUE TITLE
说我token无效怎么办

### ISSUE THREAD

**Issue by 12316joker** [AutumnWhj/ChatGPT-wechat-bot#27]
![image](https://user-images.githubusercontent.com/120159224/206631228-c8462f7e-b60f-44a9-8468-84ffddc1ce3f.png)
[](url)

**Comment by 20080217** [comment]
我也是同样的情况

**Comment by AutumnWhj** [comment]
@20080217 @12316joker  您好，试试这个https://github.com/AutumnWhj/ChatGPT-wechat-bot/issues/24 在devtool 清空浏览器缓存，重新获取session token试试。
