### ISSUE TITLE
微信群组中要如何使用？

### ISSUE THREAD

**Issue by Oosl** [AutumnWhj/ChatGPT-wechat-bot#3]
如题，我刚使用你的仓库成功搭建起来了，私聊对话验证过了，可以正常试用，但是群聊消息中不会回复任何信息，即使@bot也没用，后台log能看到收到消息。

所以想问问需要怎么操作？

**Comment by AutumnWhj** [comment]
目前demo里面没支持，可以参考一下文档 https://wechaty.js.org/docs/api/room 来实现。

**Comment by Oosl** [comment]
好的，明白。谢了！

**Comment by AutumnWhj** [comment]
@Oosl  have support, you can pull the latest code 可以拉一下代码 我写了

**Comment by Oosl** [comment]
> @Oosl have support, you can pull the latest code 可以拉一下代码 我写了

肝起来了！这就试试

**Comment by 17huiwei** [comment]
好像还是没有反应，私聊没问题，不知道其他同学能不能在群里通过关键词唤起

**Comment by kbwzy** [comment]
有群聊通过关键词唤醒成功的吗？能详细介绍下怎么设置吗？
