### ISSUE TITLE
docker build异常

### ISSUE THREAD

**Issue by JaneConan** [AutumnWhj/ChatGPT-wechat-bot#30]
![image](https://user-images.githubusercontent.com/26090153/206728076-8bb40e12-a0b0-45cf-b99c-e8a06393be89.png)

卡在npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau

很长时间，没有响应

**Comment by HenryHengLUO** [comment]
Me too. Have you solved this problem?
