### ISSUE TITLE
希望增加ARM 服务器编译

### ISSUE THREAD

**Issue by GeekWorkCode** [AutumnWhj/ChatGPT-wechat-bot#39]
Step 4/8 : RUN npm i   && npm run puppet-install
 ---> Running in b2b515e31297
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated puppeteer@13.7.0: < 18.1.0 is no longer supported
npm notice 
npm notice New major version of npm available! 8.19.2 -> 9.2.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.2.0>
npm notice Run `npm install -g npm@9.2.0` to update!
npm notice 
npm ERR! code 1
npm ERR! path /code/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! The chromium binary is not available for arm64.
npm ERR! If you are on Ubuntu, you can install with: 
npm ERR! 
npm ERR!  sudo apt install chromium
npm ERR! 
npm ERR! 
npm ERR!  sudo apt install chromium-browser
npm ERR! 
npm ERR! /code/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:119
npm ERR!                     throw new Error();
npm ERR!                     ^
npm ERR! 
npm ERR! Error
npm ERR!     at /code/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:119:27
npm ERR!     at FSReqCallback.oncomplete (node:fs:202:21)

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-10T09_11_44_972Z-debug-0.log
The command '/bin/sh -c npm i   && npm run puppet-install' returned a non-zero code: 1

**Comment by ashengjiang** [comment]
我在mac M1 的系中运行，也出现了这中问题，请问有解决的办法吗

**Comment by AutumnWhj** [comment]
@ashengjiang @GeekWorkCode  已解决  拉最新代码 执行 docker build --pull --rm -f "Dockerfile" -t wechatbot:latest "." --platform linux/amd64
