### ISSUE TITLE
请问怎么激活群里的机器人呢

### ISSUE THREAD

**Issue by cpt-kenvie** [AutumnWhj/ChatGPT-wechat-bot#47]
请问怎么激活群里的机器人呢，设置了关键字唤醒，只有私聊会回复，但群聊提示这个

```
Group name: 天天学习好好向上 talker: kenvie content: 小爱同学 你好
Content is not within the scope of the customizition format
```

**Comment by DarkTan** [comment]
好像1小时前的版本还可以用，不知道改了啥，最新的没法用了

**Comment by AutumnWhj** [comment]
你好 检查一下这个配置 @DarkTan @cpt-kenvie  为空就不限制。
<img width="514" alt="image" src="https://user-images.githubusercontent.com/39156049/206853332-70594927-3f62-4ead-8cf7-59cdb6906530.png">
