### ISSUE TITLE
能否支持群聊@回复

### ISSUE THREAD

**Issue by yangchuansheng** [AutumnWhj/ChatGPT-wechat-bot#5]

**Comment by AutumnWhj** [comment]
@yangchuansheng  已支持 可拉取代码试试  https://github.com/AutumnWhj/ChatGPT-wechat-bot/commit/2020248f1a0489ca6a298e79a593342dd570cbe5

**Comment by Oosl** [comment]
https://github.com/wechaty/wechaty/issues/2149  
这里似乎有提及

**Comment by Oosl** [comment]
破案了，目前使用的puppet: `wechaty-puppet-wechat` 是用的wechat协议，不支持@提示  
![image](https://user-images.githubusercontent.com/27420243/206073360-dc900921-4b87-4411-9893-fd14d230a10c.png)
要么换协议（但是我这个号别的可能登陆不了）
要么通过[检测消息中的字符匹配@](https://github.com/wechaty/wechaty/issues/1991)

**Comment by AutumnWhj** [comment]
<img width="586" alt="image" src="https://user-images.githubusercontent.com/39156049/206073946-f7128b16-cdac-4624-8b2c-1e2208fe9eeb.png">
<img width="967" alt="image" src="https://user-images.githubusercontent.com/39156049/206074329-27870c6f-b5e3-4ad9-b24e-ccbee43e6663.png">

@Oosl 你不行吗？ 我在群组里面用似乎正常的

**Comment by parcool** [comment]
@Oosl 不懂前端，怎么处理？？？可以监听到消息，没有response。但是单聊是没问题的。
<img width="733" alt="image" src="https://user-images.githubusercontent.com/12092478/206099689-3158867c-aa30-48f8-97e6-3db7896d01ab.png">

**Comment by Oosl** [comment]
@parcool 我也不懂前端。
不过你图里这个问题和我上面说的一样（at的bot名字有空格），可以看到你在群里@的时候，根本没有进入到检测到at消息的判断里。
解决办法就是把你微信bot的名字或者群里你微信bot的昵称改成不包含空格就行了

**Comment by parcool** [comment]
@Oosl 那已经进群了的怎么刷新？改了不带空格的也还是老是不更新

**Comment by Oosl** [comment]
@parcool 不明白你所说的“已经进群的怎么刷新”和“老是不更新”是说的什么问题

**Comment by parcool** [comment]
@parcool 改昵称里空格之前就已经进了的群，就算把这个昵称的空格删掉。别的群成员那边也是不会主动刷新的，会一直显示旧的带空格的名称。

**Comment by parcool** [comment]
> @parcool 不明白你所说的“已经进群的怎么刷新”和“老是不更新”是说的什么问题

@Oosl 改昵称里空格之前就已经进了的群，就算把这个昵称的空格删掉。别的群成员那边也是不会主动刷新的，会一直显示旧的带空格的名称。

**Comment by Oosl** [comment]
> > @parcool 不明白你所说的“已经进群的怎么刷新”和“老是不更新”是说的什么问题
> 
> @Oosl 改昵称里空格之前就已经进了的群，就算把这个昵称的空格删掉。别的群成员那边也是不会主动刷新的，会一直显示旧的带空格的名称。

退了重进？这就和本项目无关了，是微信的臭毛病，我这边没遇到。
