### ISSUE TITLE
npm run build后没有二维码

### ISSUE THREAD

**Issue by LaoCaigou** [AutumnWhj/ChatGPT-wechat-bot#55]
![image](https://user-images.githubusercontent.com/86348939/206864066-5ae79b59-e2f9-42d1-b537-2f9ceff32a8c.png)

**Comment by AutumnWhj** [comment]
还得执行node lib/bundle.esm.js

**Comment by LaoCaigou** [comment]
是需要注册账号吗
![image](https://user-images.githubusercontent.com/86348939/206864367-0242f920-beed-45e5-9cc2-9aab64831d3c.png)

**Comment by SnapdragonLee** [comment]
> 

需要配置 config.ts，readme 步骤一步一步来就可以了
