### ISSUE TITLE
为什么要开通微信支付之后才能用啊

### ISSUE THREAD

**Issue by ynpl** [AutumnWhj/ChatGPT-wechat-bot#6]
<img width="883" alt="Xnip2022-12-06_23-24-34" src="https://user-images.githubusercontent.com/28553357/205952799-2f64b48f-816d-4d72-8001-80c8cfe0c44c.png">

**Comment by yanshibin** [comment]
这是由于web登录需要这个。。。

**Comment by AutumnWhj** [comment]
@ynpl  是的  puppet-wechat有个issue有提到 https://github.com/wechaty/puppet-wechat/issues/136
