### ISSUE TITLE
发现个问题，群内机器人改了备注以后无法识别消息

### ISSUE THREAD

**Issue by PeterChen1997** [AutumnWhj/ChatGPT-wechat-bot#65]

**Comment by PeterChen1997** [comment]
看了下代码，应该是 wechaty 的实现问题，目前不怎么维护了好像 😂

**Comment by SnapdragonLee** [comment]
正确的，如果可以保证自己的昵称有一定可循性，比如没有空格，没有唤醒关键词，可以使用正则表达式重写规则，目前的规则要求群聊中的bot必须与个人名字相同

**Comment by PeterChen1997** [comment]
get

**Comment by huanzhijin** [comment]
群里好像唤醒不来，没改备注

**Comment by SnapdragonLee** [comment]
> 群里好像唤醒不来，没改备注

是的，可以参考我的发起pull request的仓库先进行测试，如果还有bug欢迎反馈
