### ISSUE TITLE
微信文本截断

### ISSUE THREAD

**Issue by Feng4** [AutumnWhj/ChatGPT-wechat-bot#67]
由于chatGPT返回的文字很多，转到微信时，有一部分文字被截断，导致不完整输出。使用 请继续   chatGPT回复无法联系上下文。这应该是微信无法输入太多字符导致的，希望大佬考虑一下这一块的解决方案。

**Comment by Feng4** [comment]
![image](https://user-images.githubusercontent.com/27730186/206895199-434b0835-c31d-441d-8776-7b2901dfabb6.png)

**Comment by SnapdragonLee** [comment]
印象里面是支持context的，代码有没有更新到最新？
