### ISSUE TITLE
返回的内容缺少了部分数据

### ISSUE THREAD

**Issue by fatyoge** [AutumnWhj/ChatGPT-wechat-bot#7]
原版页面返回：
![image](https://user-images.githubusercontent.com/3599579/205954391-2364328c-a14e-4414-bead-ce099bd863ea.png)

wechaty接入后的返回：
![image](https://user-images.githubusercontent.com/3599579/205954662-f1bc422b-501f-4b99-a4e0-e55c8a64c4ab.png)

**中间代码的部分缺了，大佬看看有办法解决吗？**

**Comment by AutumnWhj** [comment]
@fatyoge 已修复 pushed
