### ISSUE TITLE
ChatGPT failed to refresh auth token. Error: 403 Forbidden

### ISSUE THREAD

**Issue by jwu-au** [AutumnWhj/ChatGPT-wechat-bot#79]
```
wechatbot    | retry 1 times, error: Error: ChatGPT failed to refresh auth token. Error: 403 Forbidden
wechatbot    | retry 2 times, error: Error: ChatGPT failed to refresh auth token. Error: 403 Forbidden
wechatbot    | retry 3 times, error: Error: ChatGPT failed to refresh auth token. Error: 403 Forbidden
```
it was working well last night, and tried to refill the token, presented above error.

**Comment by listonlam** [comment]
i have the same question this morning..

**Comment by arong-me** [comment]
我也遇到这种问题了，请问你是解决了吗？如何解决的

**Comment by SnapdragonLee** [comment]
The auth token need to refresh manually per 1 day.

**Comment by magicknight** [comment]
奇怪，在 dev 下面清空了所有的东西，重新登陆，拿到的 token 也不行

**Comment by EnochYe** [comment]
同样在今天早上遇到了这个问题，是chatGPT网站改策略了吗？

**Comment by magicknight** [comment]
chatGPT 开启了 Cloudflare 保护。现在暂时不能用了。

**Comment by EnochYe** [comment]
邮件已收到，祝好！

**Comment by lixiaolongxl** [comment]
请问解决了吗？我也遇到了这个问题

**Comment by nuoyi66** [comment]
我的现在也一样

**Comment by rpdg** [comment]
chatgpt加了Cloudflare 保护，自行更新到 chatgpt-api 2.1.1 即可解决

**Comment by linnjoy** [comment]
> chatgpt加了Cloudflare 保护，自行更新到 chatgpt-api 2.1.1 即可解决

怎么更新到2.1.1？

**Comment by adbchen** [comment]
> > chatgpt加了Cloudflare 保护，自行更新到 chatgpt-api 2.1.1 即可解决
> 
> 怎么更新到2.1.1？

![image](https://user-images.githubusercontent.com/50573096/206954037-ba63eef9-4f2f-487e-9e6e-cba30f3ebfd6.png)

**Comment by AutumnWhj** [comment]
chatGPT 开启了 Cloudflare 保护。现在暂时不能用了。 https://github.com/transitive-bullshit/chatgpt-api/issues/96
小伙伴们可尝试一下这种方法
https://github.com/transitive-bullshit/chatgpt-api#update-december-11-2022

**Comment by icarsone** [comment]
> 
When i add ClearenceToken in the API，it has errors below：
It means we have not defined this type，but i have no idea where to add this argument type
```
 Plugin typescript: @rollup/plugin-typescript TS2345: Argument of type '{ sessionToken: string; clearanceToken: string; userAgent: string; }' is not assignable to parameter of type '{ sessionToken: string; markdown?: boolean | undefined; apiBaseUrl?: string | undefined; backendApiBaseUrl?: string | undefined; userAgent?: string | undefined; accessTokenTTL?: number | undefined; }'.
  Object literal may only specify known properties, and 'clearanceToken' does not exist in type '{ sessionToken: string; markdown?: boolean | undefined; apiBaseUrl?: string | undefined; backendApiBaseUrl?: string | undefined; userAgent?: string | undefined; accessTokenTTL?: number | undefined; }'.
```

**Comment by icarsone** [comment]
Oops！I have not update the independence，after i run `npm i`，this error disappear.
But it still have 403 Forbidden

**Comment by icarsone** [comment]
> Fine，I know the reason now
`Your user-agent and IP address must match from the real browser window you're logged in with to the one you're using for ChatGPTAPI.
This means that you currently can't log in with your laptop and then run the bot on a server or proxy somewhere.`

**Comment by li1243893836** [comment]
I filled in the corresponding chatGPTSessionToken, clearanceToken and userAgent, but received a message and still reported 403 Forbidden
![image](https://user-images.githubusercontent.com/56986669/206983306-fb340b8a-11bf-413a-9862-2ccc0ad4ca37.png)
![image](https://user-images.githubusercontent.com/56986669/206983361-fea08550-3f4f-47ba-921b-f223399c4d09.png)

Which boss can solve the problem

**Comment by Zytxjnn** [comment]
和你一样的的问题，还没解决，哎
![image](https://user-images.githubusercontent.com/45702802/208049076-8d576af2-a5b0-4386-af99-3435f8bbc0d7.png)

**Comment by adbchen** [comment]
用国外服务器，浏览器登录的ip和本地代码请求的ip不一样




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月16日(星期五) 下午3:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AutumnWhj/ChatGPT-wechat-bot] ChatGPT failed to refresh auth token. Error: 403 Forbidden (Issue #79)





 
和你一样的的问题，还没解决，哎

**Comment by jackslet** [comment]
SAME OLD SAME OLD. FOR MANY DAYS

**Comment by YIEHOO** [comment]
Same issue here

**Comment by EnochYe** [comment]
邮件已收到，祝好！

**Comment by EnochYe** [comment]
邮件已收到，祝好！
