### ISSUE TITLE
有遇到这种错误吗？ChatGPTError: ChatGPT failed to refresh auth token. Error: 403 Forbidden

### ISSUE THREAD

**Issue by zero1169068213** [AutumnWhj/ChatGPT-wechat-bot#85]
![image](https://user-images.githubusercontent.com/45230059/206989947-1c552b06-932b-4d6b-bbda-494a6aeb6721.png)
![image](https://user-images.githubusercontent.com/45230059/207000840-e2d39a21-3457-45eb-a44a-2d6452cee12b.png)

**Comment by MasonKuo** [comment]
解决了吗，我也是这个错误

**Comment by zero1169068213** [comment]
> 解决了吗，我也是这个错误

还没有

**Comment by 13146248578** [comment]
+1

**Comment by DamonZX** [comment]
+1

**Comment by CaicoLeung** [comment]
+1

**Comment by liuliangsir** [comment]
+1

**Comment by liuliangsir** [comment]
Same issue here. Here is a solution.
<img width="890" alt="image" src="https://user-images.githubusercontent.com/8049878/211162024-0c856859-5248-4142-8a13-aabebb0dbcf5.png">
