### ISSUE TITLE
有人微信封号了吗？我被关小黑屋3天了

### ISSUE THREAD

**Issue by ivank-s** [AutumnWhj/ChatGPT-wechat-bot#92]

**Comment by AutumnWhj** [comment]
微信会以”使用第三方软件、外挂、插件等非官方工具或其他违规行为“为理由进行封号，最好用小号。

**Comment by hawx1993** [comment]
+1，会被关小黑屋的

**Comment by jtia123** [comment]
被警告了+1

**Comment by AK47BIU** [comment]
被警告了，有解决办法吗

**Comment by AirSkye** [comment]
用内存注入的方式hookPC端一般不会被检测到，比较安全，扫码的一测一个准。

**Comment by forever85** [comment]
哦，那我不玩了，反正没成功

**Comment by Hunter-0x07** [comment]
我也被警告强制下线了一波

**Comment by hhy885** [comment]
> 用内存注入的方式hookPC端
能分享一下咋注入的么？谢了

**Comment by Hanson** [comment]
https://github.com/hanson/vbot 这个不封号

**Comment by cjy0812** [comment]
测试a账号app只改包名，警告两次，一天一次。原版8.0.48
b账号原包名但注入了，警告两次，第二次警告隔了一天版本play8.0.33。
而我之前有root手机通过hook方式三年均没警告过
结论：微信会检查签名，不一致就很大概率封号
